name: "Publish GitHub Action"
on:
  push:
    branches:    
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: tgymnich/publish-github-action@v1.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}